extends SceneTree

const HUD_SCRIPT := preload("res://src/ui/HUD.gd")
const BUBBLE_SCRIPT := preload("res://src/ui/GlossyWorldBubble.gd")


func _init() -> void:
	call_deferred("_run")


func _run() -> void:
	for path in [
		ProductionUIAssets.LEVEL_BADGE,
		ProductionUIAssets.IDENTITY_PANEL,
		ProductionUIAssets.RESOURCE_CHIP,
		ProductionUIAssets.WORLD_BUBBLE,
		ProductionUIAssets.BUTTON_GREEN,
		ProductionUIAssets.BUTTON_BLUE,
		ProductionUIAssets.BUTTON_GRAY,
		ProductionUIAssets.PROGRESS_TRACK,
		ProductionUIAssets.PROGRESS_BLUE,
		ProductionUIAssets.PROGRESS_GOLD
	]:
		if not ResourceLoader.exists(path):
			_fail("Missing production UI asset: %s" % path)
			return
		if ProductionUIAssets.texture(path) == null:
			_fail("Production UI asset failed to import: %s" % path)
			return

	var hud = HUD_SCRIPT.new()
	root.add_child(hud)
	await process_frame

	hud.set_player_data(12, 12340, 37)
	hud.set_level_progress(1250, 0, 2000)
	hud.set_passenger_data(842, 1000, 2.0)
	hud.set_fuel_data(180, 360, 1.6)

	if hud.level_label.text != "12":
		_fail("Level badge should use a code-driven level number.")
		return
	if absf(hud.xp_progress.value - 1250.0) > 0.01:
		_fail("XP bar fill should be driven by runtime XP.")
		return
	if hud.xp_label.text != "1,250/2,000":
		_fail("XP text should be generated by code.")
		return
	if hud.passenger_label.text != "842 / 1000":
		_fail("Passenger value should be generated by code.")
		return
	if hud.fuel_label.text != "180 / 360":
		_fail("Fuel value should be generated by code.")
		return

	if not (hud.xp_progress.get_theme_stylebox("background") is StyleBoxTexture):
		_fail("XP bar should use the production textured track.")
		return
	if not (hud.xp_progress.get_theme_stylebox("fill") is StyleBoxTexture):
		_fail("XP bar should use a production textured fill.")
		return
	if not (hud.fuel_order_button.get_theme_stylebox("normal") is StyleBoxTexture):
		_fail("Fuel order should retain a real glossy interactive button.")
		return

	var bubble = BUBBLE_SCRIPT.new()
	root.add_child(bubble)
	await process_frame
	bubble.configure(
		"Fuel",
		"180 / 360",
		"+1.6 / min",
		null,
		"+",
		0.5
	)
	if bubble.value_label.text != "180 / 360":
		_fail("Reusable bubble value should remain code-driven.")
		return
	if absf(bubble.progress_bar.value - 0.5) > 0.001:
		_fail("Reusable bubble progress should remain code-driven.")
		return
	if not (bubble.get_theme_stylebox("panel") is StyleBoxTexture):
		_fail("World bubble should use the production speech-bubble skin.")
		return

	print(
		"PRODUCTION_UI_SKIN_OK dynamic_numbers=true dynamic_xp=true "
		+ "glossy_buttons=true reusable_bubbles=true"
	)
	quit(0)


func _fail(message: String) -> void:
	push_error(message)
	quit(1)
